#!/usr/bin/env python
"""Write a markdown table of every flake package and its metadata.

Usage:
  freezedocs                  Writes PACKAGES.md at the repo root
  freezedocs -o docs/pkgs.md  Writes to a custom output path
"""
import argparse
import json
import os
import subprocess

NIX_APPLY = """
ps: builtins.mapAttrs (n: p:
  let m = p.meta or {};
  in {
    pname = p.pname or n;
    version = p.version or "unknown";
    description = m.description or "";
    homepage = m.homepage or "";
    license = m.license or null;
  }) ps
"""


def run_out(cmd):
    return subprocess.check_output(cmd, text=True).strip()


def current_system():
    return run_out(["nix", "eval", "--impure", "--raw", "--expr", "builtins.currentSystem"])


def fetch(system):
    out = run_out(["nix", "eval", "--json", f".#packages.{system}", "--apply", NIX_APPLY])
    return json.loads(out)


def fmt_license(lic):
    """meta.license may be missing, a string, an attrset, or a list of either."""
    if not lic:
        return "—"
    items = lic if isinstance(lic, list) else [lic]
    names = []
    for item in items:
        if isinstance(item, str):
            names.append(item)
        elif isinstance(item, dict):
            names.append(item.get("spdxId") or item.get("shortName") or item.get("fullName") or "unknown")
    return ", ".join(names) or "—"


def fmt_homepage(hp):
    if isinstance(hp, list):
        hp = hp[0] if hp else ""
    return f"<{hp}>" if hp else "—"


def fmt_platforms(plats):
    return ", ".join(f"`{p}`" for p in plats) if plats else "—"


def cell(text):
    """Make a string safe for a markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip() or "—"


def render(pkgs):
    lines = [
        "<!-- Generated by frosty-docgen. Do not edit by hand. -->",
        "# Packages",
        "",
        "| Package | Version | Description | Homepage |  License |",
        "| --- | --- | --- | --- | --- |",
    ]
    for attr in sorted(pkgs):
        p = pkgs[attr]
        lines.append(
            "| " + " | ".join(
                [
                    cell(f"`{p['pname']}`"),
                    cell(p["version"]),
                    cell(p["description"]),
                    cell(fmt_homepage(p["homepage"])),
                    cell(fmt_license(p["license"])),
                ]
            ) + " |"
        )
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("-o", "--output", default="PACKAGES.md")
    opts = parser.parse_args()

    os.chdir(run_out(["git", "rev-parse", "--show-toplevel"]))
    pkgs = fetch(current_system())

    with open(opts.output, "w") as fh:
        fh.write(render(pkgs))
    print(f"Wrote {len(pkgs) - 2} packages to {opts.output}")


if __name__ == "__main__":
    main()
